# Generated by Django 4.1.5 on 2023-04-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_disponible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='color',
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default='XXXX', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='ndepuertas',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='patente',
            field=models.CharField(default='XXXX', max_length=200),
            preserve_default=False,
        ),
    ]
