# Generated by Django 4.1.7 on 2023-05-09 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_rename_nombre_producto_color_producto_modelo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='modelo',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='ordenproducto',
            name='orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenproducto_set', to='tienda.orden'),
        ),
    ]
